### ISSUE TITLE
Valence values sticking

### ISSUE THREAD

**Issue by blockale23** [ehng359/functional_fashion_watch#3]
Some valence values sticking - only noticed with negative values around -0.28 and -0.35 sometimes wouldn't "refresh" and "snap" back to the 0.000 after the 5 seconds with new HR

**Comment by ehng359** [comment]
Is this issue occurring on the event that you're continually dragging? Or is this occurring on the onset of setting it and then leaving to do other things? 

There does exist the possibility where your watch goes to sleep once you've set the value which makes the display stop updating as frequently (but the logic behind everything remains the same). I looked at the data file you provided and there wasn't a situation where there was high levels of repetition of values consecutively.

**Comment by ehng359** [comment]
Also note: current implementation indicates that if you're not currently recording, the line will not reset to 0 since no values have been sent.
