### ISSUE TITLE
Difficult selecting valence and activity options

### ISSUE THREAD

**Issue by blockale23** [ehng359/functional_fashion_watch#4]
I had a really difficult time scrolling through and selecting different valence and activity options. 

I think they are too close together and there is not enough room at the bottom after the activity. 

I think it would be easier if you clicked it once and all the options popped out as a list and you tapped the one you wanted to select rather than scrolling, because right now I'm finding it really difficult.

**Comment by ehng359** [comment]
I will be doing a UI-overhaul shortly because of the fact that ScrollView in Swift has terrible interactivity with the picker method chosen.

**Comment by ehng359** [comment]
Resolved in https://github.com/ehng359/functional_fashion_watch/commit/674bfb5aa5aa65025a8f058ec9e4d193db7be4d7.
