### ISSUE TITLE
Static server

### ISSUE THREAD

**Issue by blockale23** [ehng359/functional_fashion_watch#5]
Since we're always sending to the same server https://biometrics.uclalemur.com do you think you can autofill that either in a drop down menu we can select or just have it pre-filled in such that we don't need to manually type it in each time?

**Comment by blockale23** [comment]
Hey can we do this? It's a little annoying to always have to type in the full name of the server. It would be a lot better if it was automatically input in there for you, or if at least it was in a drop-down menu that you could just click on it so you didn't have to type it in. It would significantly reduce the time it takes to set up and result in me being able to/wanting to record more data. 

Thanks!

**Comment by ehng359** [comment]
Default enabled in https://github.com/ehng359/functional_fashion_watch/commit/bcfe0a3c1b32e1d105e224f936e816377227d980
